"""add attempts column to otp_codes

Revision ID: 02c00a466883
Revises: d4cffd3faecd
Create Date: 2026-09-07 19:27:03.871937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c00a466883'
down_revision: Union[str, Sequence[str], None] = 'd4cffd3faecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('attempts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'attempts')
    # ### end Alembic commands ###
