"""add status_message and updated_at to responses

Revision ID: 691e5504531d
Revises: da093877a6db
Create Date: 2026-09-10 19:16:51.847862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691e5504531d'
down_revision: Union[str, Sequence[str], None] = 'da093877a6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('status_message', sa.String(), nullable=True))
    op.add_column('responses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'updated_at')
    op.drop_column('responses', 'status_message')
    # ### end Alembic commands ###
