// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fLhdccixYHBJau1aBUsx2Eyu57KvMUQ',
    appId: '1:190821088244:web:429094ec828ebc97a957a1',
    messagingSenderId: '190821088244',
    projectId: 'blood-response-system',
    authDomain: 'blood-response-system.firebaseapp.com',
    storageBucket: 'blood-response-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CdOWhU2i9fzFq8Szcfo4LJJoTQvSt6Q',
    appId: '1:190821088244:android:d793cf9006e11d45a957a1',
    messagingSenderId: '190821088244',
    projectId: 'blood-response-system',
    storageBucket: 'blood-response-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjDTShssQ2uDVJB9JO--LIZ_nFmfnpwb0',
    appId: '1:190821088244:ios:9c9fd77bfdb8a8aca957a1',
    messagingSenderId: '190821088244',
    projectId: 'blood-response-system',
    storageBucket: 'blood-response-system.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjDTShssQ2uDVJB9JO--LIZ_nFmfnpwb0',
    appId: '1:190821088244:ios:9c9fd77bfdb8a8aca957a1',
    messagingSenderId: '190821088244',
    projectId: 'blood-response-system',
    storageBucket: 'blood-response-system.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5fLhdccixYHBJau1aBUsx2Eyu57KvMUQ',
    appId: '1:190821088244:web:7fa1ec8b976b4ce6a957a1',
    messagingSenderId: '190821088244',
    projectId: 'blood-response-system',
    authDomain: 'blood-response-system.firebaseapp.com',
    storageBucket: 'blood-response-system.firebasestorage.app',
  );
}
